version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Starting installation phase"
  pre_build:
    commands:
      - echo "Pre-build phase starting"
      - echo "Verifying AWS access"
      - aws sts get-caller-identity
      - echo "Installing kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - kubectl version --client
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask
      - echo "Setting up kubeconfig"
      - aws eks update-kubeconfig --region us-east-1 --name project-cluster
  build:
    commands:
      - echo "Build phase starting"
      - echo "Checking current directory and files"
      - pwd
      - ls -la
      - echo "Checking if Dockerfile exists"
      - cat Dockerfile || echo "Dockerfile not found"
      - echo "Checking dist directory"
      - ls -la dist/ || echo "dist directory not found"
      - echo "Building Docker image"
      - docker build -t braintask . || echo "Docker build failed"
      - echo "Checking if image was created"
      - docker images | grep braintask || echo "Image not found"
      - echo "Tagging Docker image"
      - docker tag braintask:latest 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest || echo "Tagging failed"
  post_build:
    commands:
      - echo "Post-build phase starting"
      - echo "Pushing image to ECR"
      - docker push 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest
      - echo "Preparing for deployment"
      - echo "Testing kubectl connectivity"
      - kubectl get nodes || echo "Cannot get nodes"
      - kubectl get namespaces || echo "Cannot get namespaces"
      - echo "Checking k8s files"
      - ls -la k8s/
      - echo "Contents of deployment.yaml:"
      - cat k8s/deployment.yaml
      - echo "Contents of service.yaml:"
      - cat k8s/service.yaml
      - echo "Validating manifests"
      - kubectl apply --dry-run=client -f k8s/deployment.yaml || echo "Deployment validation failed"
      - kubectl apply --dry-run=client -f k8s/service.yaml || echo "Service validation failed"
      - echo "Applying deployment"
      - kubectl apply -f k8s/deployment.yaml || echo "Deployment apply failed"
      - echo "Applying service"
      - kubectl apply -f k8s/service.yaml || echo "Service apply failed"
      - echo "Checking final status"
      - kubectl get deployments || echo "Cannot get deployments"
      - kubectl get services || echo "Cannot get services"
      - kubectl get pods || echo "Cannot get pods"
