version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://s3.us-east-1.amazonaws.com/amazon-eks/1.29.0/2024-05-31/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992757690557.dkr.ecr.us-east-1.amazonaws.com
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name kubernetes-task-cluster --region us-east-1 || exit 1
      - echo Verifying kubectl can talk to the cluster...
      - kubectl get nodes || exit 1
  build:
    commands:
      - echo Building Docker image...
      - docker build -t miniproject1/braintask .
      - docker tag miniproject1/braintask:latest 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest
      - echo Deploying to EKS...
      - kubectl apply -f k8s/
