version: 0.2

env:
  variables:
    CLUSTER_NAME: "project-cluster"
    AWS_REGION: "us-east-1"
    ECR_REPO: "992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask"

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO https://s3.us-east-1.amazonaws.com/amazon-eks/1.29.0/2024-05-31/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Checking identity..."
      - aws sts get-caller-identity

      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - echo "Configuring kubectl for EKS..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - echo "Verifying EKS access..."
      - kubectl get nodes

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t braintask .
      - docker tag braintask:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPO:latest

      - echo "Deploying to EKS..."
      - kubectl apply -f k8s/
