version: 0.2
env:
  variables:
    CLUSTER_NAME: "project-cluster"
    AWS_REGION: "us-east-1"
    ECR_REPO: "992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask"
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
      # Update package manager
      - apt-get update -y
      - apt-get install -y unzip curl
      # Install AWS CLI v2
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install --update
      - aws --version
      # Install kubectl
      - echo "Installing kubectl..."
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "kubectl installed successfully"
  pre_build:
    commands:
      - echo "Verifying AWS access..."
      - aws sts get-caller-identity
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo "Setting up kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - echo "Testing kubectl..."
      - kubectl version --client || echo "kubectl client version check complete"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t braintask .
      - docker tag braintask:latest $ECR_REPO:latest
      - echo "Build completed successfully"
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPO:latest
      - echo "Image pushed successfully"
      - echo "Deploying to EKS..."
      - kubectl apply -f k8s/
      - echo "Deployment completed"
      - echo "Getting deployment status..."
      - kubectl get deployments
      - kubectl get services
