version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Starting installation phase"
  pre_build:
    commands:
      - echo "Pre-build phase starting"
      - echo "Verifying AWS access"
      - aws sts get-caller-identity
      - echo "Installing kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - kubectl version --client
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask
      - echo "Setting up kubeconfig"
      - aws eks update-kubeconfig --region us-east-1 --name project-cluster
  build:
    commands:
      - echo "Build phase starting"
      - echo "Building Docker image"
      - docker build -t braintask .
      - echo "Tagging Docker image"
      - docker tag braintask:latest 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest
  post_build:
    commands:
      - echo "Post-build phase starting"
      - echo "Pushing image to ECR"
      - docker push 992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask:latest
      - echo "Deploying to EKS"
      - kubectl apply -f k8s/
      - echo "Checking deployment status"
      - kubectl get deployments
      - kubectl get services
