version: 0.2

env:
  variables:
    CLUSTER_NAME: "project-cluster"
    AWS_REGION: "us-east-1"
    ECR_REPO: "992757690557.dkr.ecr.us-east-1.amazonaws.com/miniproject1/braintask"

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO https://s3.us-east-1.amazonaws.com/amazon-eks/1.29.0/2024-05-31/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "kubectl installed."

  pre_build:
    commands:
      - echo "Authenticating with ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - echo "Verifying EKS access..."
      - aws sts get-caller-identity
      - aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION
      - kubectl version --short
      - kubectl get nodes

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t braintask .
      - docker tag braintask:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPO:latest

      - echo "Deploying to EKS..."
      - |
        if [ -d "k8s" ]; then
          kubectl apply -f k8s/
        else
          echo "k8s/ directory not found, skipping deployment."
        fi
